<script type="text/javascript">
    try {
        (function () {
            if (typeof fittipaldi == 'undefined') {
                var fittipaldi = document.createElement('script');
                fittipaldi.type = 'text/javascript';
                fittipaldi.async = true;
                fittipaldi.id = "fittipaldi";
                fittipaldi.src = "https://df.fcontrol.com.br/js/fittipaldiJs.js";
                document.documentElement.firstChild.appendChild(fittipaldi);
            }
        })();
    } catch (err) { }
</script>